// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package es.valenciajug.sorteo.repository;

import es.valenciajug.sorteo.repository.PersonRepository;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PersonRepository_Roo_Jpa_Repository {
    
    declare @type: PersonRepository: @Transactional(readOnly = true);
    
}
